before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X "main.Version=v{{ .Version }}" -X "main.GitCommit={{ .FullCommit }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - image_templates: ["jaymedh/{{ .ProjectName }}:v{{ .Version }}-amd64"]
    dockerfile: Dockerfile
    use: buildx
    extra_files:
      - passwd
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/jayme-github/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/jayme-github/{{ .ProjectName }}
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=GPLv3
  - image_templates: ["jaymedh/{{ .ProjectName }}:v{{ .Version }}-arm64v8"]
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    extra_files:
      - passwd
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/jayme-github/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/jayme-github/{{ .ProjectName }}
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=GPLv3
docker_manifests:
  - name_template: jaymedh/{{ .ProjectName }}:v{{ .Version }}
    image_templates:
      - jaymedh/{{ .ProjectName }}:v{{ .Version }}-amd64
      - jaymedh/{{ .ProjectName }}:v{{ .Version }}-arm64v8
  - name_template: jaymedh/{{ .ProjectName }}:latest
    image_templates:
      - jaymedh/{{ .ProjectName }}:v{{ .Version }}-amd64
      - jaymedh/{{ .ProjectName }}:v{{ .Version }}-arm64v8
