language: go
dist: focal
sudo: required

env:
  global:
    - CGO_ENABLED=0
    - GO111MODULE=on
    - secure: "sMxNiZYfdCW8RoitjsmDtPiI/fv64pBRojilqVFtB8HjZNM4b/A/3k7ApwTkk5cMVHLj4D3TQ9GBDPpKdmOfuJTX9BKhbbj6xiYnhGhYzOb6bCgxRwhJE4KCoJ5DqL3TuT6kBACwORCKpkwxz3ohKvq9whA/4JVZ9eed139UyBMhNYktrjJ4KM16Y28dY1nY98SzmT4JO7d+i/NCfqHCOGR3yxhz4QK/gKSI6D5DCfJ2jmo28Masv/OZaQYYyenJKQ0xqG4qHmNSTcHfqNV2hT5D3ihhdUmXAAFuTQkGovnGuyhEE7eZ8gIe1RO8ZrVNn7PU5GxwSGTkxHWdBnyeqsqf27qOsefID1uUdRzJgyTMSuo3sKopjRbecYfYA6G6bX5w+umAzpLLy4JvkojBH04ntkubjfezOfoJg8yd8f+AEQZV3UHH6mapPgCRu59899bjeKHNotaWFeQ1+lEnIV2Tf6gdeV9cNpvGT0rIQxQSLkGPOKr6gsToxbwTKAFg+xOkIgHLhjOkMpm5tkSZVBU++X3FuyHyUQwucCWobhG9wYO8XvgbXewOaaYvqtruoYsMyEKI38gnkwnzrecdy7aO8hN+NX8mMj07b69ePoqlNgRS6G/zIYA7q25vZ56InO1uS1hpRUJibjVSrTXchV6mhk1+Hnyt3dwm4uWV5xc="
    - secure: "Rt4/Indp+p3h/XUfkQeC/pqqvTRIN9uFpLvCGeTmdo+6Wf4q1BWCP3je8e+FknAKCTAZUcV2z9IzwvAUsXxbkPWWqXaYaezno4PcSToixYI1+A5tuwRjNgJCG8yov+/DzmYfMsIyha49Ylxjvl105Jns9WyCf1yaaiJtdekW5I4YsLiS5gzypI5IDQj3jHXdg9aHf11GURNU9p0J1s7fH9LzQpZT2KMbsnLjFuCliIUZT6yZ7gFf8FEgWNPW7f7mm+KxKnWYYRzd07jMiyFylL6gsTq39d9PLJPssu8fTHXA/lYIMRBTskQjzE7MfFFht+QgdRFMyFFNtXoKme0vO3amHtQ0luPI4uHP/V2V9dlKJ0AvxgsJ04RCVqut22SdZDzukJ/3uQ3GiVDwh9zHEHICq6xGqxRbRKNIa2h4kIjftuCO6xETSjxVatXsfAQYqkej7hr/5JJTNj4bINumBi25qwkg5JH5UkvtWHQjVIINOVS1+yUNynVr9Fl41Aq8pBAWKv8oypuJ6rBSWHUnLmiLCRGZVEr8EdvJEmwl+RJtCIbY7cFwn6S4OpUJPzEqb2MqMWbAeAFoUvnopEbuz2QIyh1RWEr98T8kuB/MAvSjpPmuFhESqx1ksC8ZQNydu5WE6JgPj5KRlCFGYddo/KYrVYqwhu4TCYatRo3u9nQ="

services:
- docker

matrix:
  include:
  - go: 1.16.x
    env:
     - LATEST=true
  - go: tip
  allow_failures:
  - go: tip

before_install:
 - mkdir -p ~/.docker/cli-plugins/
 - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
 - chmod a+x ~/.docker/cli-plugins/docker-buildx

install:
 - go mod download
 - go get github.com/mitchellh/gox

script:
 - go vet $(go list ./... | grep -v /vendor/)
 - go test -v ./...
 - if [ "${LATEST}" = "true" ]; then
   gox -os="darwin" -os="linux" -os="windows" -arch="amd64" -arch="arm64" -osarch="linux/386" -osarch="linux/arm" -osarch="windows/386"
   -output="build/fritzbox_smarthome_exporter.{{.OS}}.{{.Arch}}" -ldflags "-extldflags \"-static\" -X main.Rev=`git rev-parse --short HEAD`" -verbose ./...;
   fi
 - if [ "${LATEST}" = "true" -a -n "${TRAVIS_TAG}" ]; then
   docker buildx create --use;
   docker buildx build --platform linux/amd64,linux/arm64,linux/arm,linux/386 -t "jaymedh/fritzbox_smarthome_exporter:${TRAVIS_TAG}" .;
   fi

deploy:
 - provider: releases
   skip_cleanup: true
   api_key:
     secure: D6zUa6GJWwyykS40t7CKitf8vuXqeGWQBpdE8cimcWmsWu158PIcEG6QNBIDBdZw8t2nxy6n9xqxKnYUYU4rw5UPu9hHCrTCEycMj07uVHvIOt74QU8js9cKjz2aD/Cm4huQDsgSIgy2mguC1qeKjjjGl4m0OKLfMWpB7F9m+1ysTKeghtRj40fzNPzVWeKOpCVBYlX/IvHBV+ObXy25dCOofoCD5QvQafRqQ6g0uRg5bqvDe9ZTly8JmbZhkc0eovxPMQQ7e8Q68nStz/ph+ME/iZEppCBc5JpDMHAlAPS4uO57ZOLsmqIZ8rBUNx+5nKy47z/ERueCezp8bwT2Bdz+SguP1IJSHNTMDilGzIC4VfKxaQE5GMwvkJG21mCG24ny2f5ZWDoXbRR7OdSN1B6wamNOfsMT/CYDfxtnoatkqhwepYtN8RWiBaMawwX/GhJib4xUM/n3lJC13K+c2q5moVdaryN270VdON4XdC+7mgZ9bklVzNFNYVAtAGlZi02AHa/BoTM73X0gtiK8JdgIXEZKLN6h3q0ufLbjRc6NAnyLiXi9B5UeTrKpx4g9lhbS9eKTvLim1gUVd2dyy3uw3mFBLXCjYhqeWzm4+8lwRwInV3iph9/raaYQ/bC7abxYO7zOo3cIeFx3NCltRLCQXpn4RQxJfYN09cYRlV8=
   file_glob: true
   file: build/fritzbox_smarthome_exporter.*
   on:
     repo: jayme-github/fritzbox_smarthome_exporter
     tags: true
     condition: "$LATEST = true"
 - provider: script
   script: bash docker_push.sh
   on:
     repo: jayme-github/fritzbox_smarthome_exporter
     tags: true
     condition: "$LATEST = true"
